name: Build and Test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: "server"

      - name: Run tests
        run: npm run jest
        working-directory: "server"

      - name: Build app
        run: npm run build
        working-directory: "server"

  deploy:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: "server"

      - name: tar artifact
        run: |
          echo "-- ls root"
          ls
          cd server
          echo "-- ls server"
          ls
          cd dist
          echo "-- ls server/dist"
          ls
          tar czf app.tar.gz server/dist/

      # - name: Generate HMAC signature
      #   id: sig
      #   run: |
      #     sig=$(openssl dgst -sha256 -hmac "$DEPLOY_SECRET" -binary app.tar.gz | xxd -p -c 256)
      #     echo "signature=$sig" >> $GITHUB_OUTPUT
      #   env:
      #     DEPLOY_SECRET: ${{ secrets.DEPLOY_USER_SSH_KEY }}

      # - name: Upload to server
      #   id: upload
      #   run: |
      #     status=$(curl -s -o /dev/null -w "%{http_code}" \
      #       -H "x_signature: ${{ steps.sig.outputs.signature }}" \
      #       -F "file=@app.tar.gz" \
      #       ${{ secrets.DEPLOY_HOST }})

      #       if [ "$status" -ne 200 ]; then
      #         echo "Deployment failed (HTTP $status)"
      #         exit 1
      #       fi

      # - name: Checkout code
      #   uses: actions/checkout@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Bump version
      #   run: |
      #     cd server
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     npm version patch --no-git-tag-version
      #     git add package.json
      #     git add package-lock.json
      #     git commit -m "chore: bump version [skip ci]"
      #     git push
